basePath: /
definitions:
  model.Book:
    properties:
      author:
        type: string
      id:
        type: string
      title:
        type: string
      year:
        type: integer
    type: object
  model.CreateBookRequest:
    properties:
      author:
        type: string
      title:
        type: string
      year:
        type: integer
    type: object
  model.Response:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  model.UpdateBookRequest:
    properties:
      author:
        type: string
      title:
        type: string
      year:
        type: integer
    type: object
info:
  contact: {}
  description: This is a swagger for Backend Test Desent
  title: Backend Test Desent API
  version: "1.0"
paths:
  /api/books:
    get:
      consumes:
      - '*/*'
      description: find all books.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Book'
            type: array
      summary: FindAll
      tags:
      - book
    post:
      consumes:
      - application/json
      description: create a new book.
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.CreateBookRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Book'
      summary: Create
      tags:
      - book
  /api/books/{id}:
    delete:
      consumes:
      - '*/*'
      description: delete a book.
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Book'
      summary: Delete
      tags:
      - book
    get:
      consumes:
      - '*/*'
      description: find a book by id.
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Book'
      summary: FindByID
      tags:
      - book
    put:
      consumes:
      - application/json
      description: update a book.
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      - description: Request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.UpdateBookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Book'
      summary: Update
      tags:
      - book
  /api/echo:
    post:
      consumes:
      - application/json
      description: echo the request.
      parameters:
      - description: Request body
        in: body
        name: body
        required: true
        schema: {}
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      summary: Echo
      tags:
      - echo
  /api/health:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: Check Health
      tags:
      - health
  /api/ping:
    get:
      consumes:
      - '*/*'
      description: ping the server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: Ping
      tags:
      - health
swagger: "2.0"
