basePath: /
definitions:
  model.Health:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  model.Response:
    properties:
      data: {}
      message:
        type: string
      status:
        type: boolean
    type: object
info:
  contact: {}
  description: This is a swagger for Backend Test Desent
  title: Backend Test Desent API
  version: "1.0"
paths:
  /api/health:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Health'
      summary: Check Health
      tags:
      - health
  /api/ping:
    get:
      consumes:
      - '*/*'
      description: ping the server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
      summary: Ping
      tags:
      - health
swagger: "2.0"
